# Run MRjs testing
name: npm run test

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    # needs: build # todo
    steps:
    - uses: actions/checkout@v4
    
      # todo - run the npm install with a dockerfile setup instead of pure
      # install but not important to do right now since install isnt too long
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Install Dependencies
      run: |
        npm install

    - name: ðŸ‘· Build
      run: npm run build
    
    # todo - have a way to run off a saved build image
    # will do after getting testing up and running 
    
    - name: ðŸ‘· Test
      run: npm test
